# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fed8c28417a14ede3566fb8193455ed2"
name = "reggio-registers-backend-api"
application_url = "https://reggio-registers-backend-api.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobjects,write_products,write_app_proxy"

[auth]
redirect_urls = [
  "https://reggio-registers-backend-api.fly.dev/auth/callback",
  "https://reggio-registers-backend-api.fly.dev/auth/shopify/callback",
  "https://reggio-registers-backend-api.fly.dev/api/auth/callback"
]

[app_proxy]
url = "/proxy_route"
subpath = "reggio-registers-backend-api"
prefix = "apps"
